/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simplex_java_Matrica */

#ifndef _Included_simplex_java_Matrica
#define _Included_simplex_java_Matrica
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simplex_java_Matrica
 * Method:    GJT
 * Signature: (Ljava/util/ArrayList;II)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_simplex_1java_Matrica_GJT
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
